
package cz.ares.basic;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Služba poskytuje XML výpis Basic ve zkratkách
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BasicService", targetNamespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl", wsdlLocation = "http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl")
public class BasicService
    extends Service
{

    private final static URL BASICSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cz.ares.basic.BasicService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cz.ares.basic.BasicService.class.getResource(".");
            url = new URL(baseUrl, "http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BASICSERVICE_WSDL_LOCATION = url;
    }

    public BasicService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BasicService() {
        super(BASICSERVICE_WSDL_LOCATION, new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl", "BasicService"));
    }

    /**
     * Port pro Http Soap rozhraní služby BasicService
     * 
     * @return
     *     returns HttpSoapBasic
     */
    @WebEndpoint(name = "BasicHttpSoapPort")
    public HttpSoapBasic getBasicHttpSoapPort() {
        return super.getPort(new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl", "BasicHttpSoapPort"), HttpSoapBasic.class);
    }

    /**
     * Port pro Http Soap rozhraní služby BasicService
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HttpSoapBasic
     */
    @WebEndpoint(name = "BasicHttpSoapPort")
    public HttpSoapBasic getBasicHttpSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl", "BasicHttpSoapPort"), HttpSoapBasic.class, features);
    }

    /**
     * Port pro Http Get rozhraní služby BasicService
     * 
     * @return
     *     returns HttpGetBasic
     */
    @WebEndpoint(name = "BasicHttpGetPort")
    public HttpGetBasic getBasicHttpGetPort() {
        return super.getPort(new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl", "BasicHttpGetPort"), HttpGetBasic.class);
    }

    /**
     * Port pro Http Get rozhraní služby BasicService
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HttpGetBasic
     */
    @WebEndpoint(name = "BasicHttpGetPort")
    public HttpGetBasic getBasicHttpGetPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl", "BasicHttpGetPort"), HttpGetBasic.class, features);
    }

}
