
package cz.ares.basic;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Ares_odpovedi", targetNamespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer_basic/v_1.0.3")
public class GetHttpBasicFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AresOdpovedi faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetHttpBasicFault(String message, AresOdpovedi faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetHttpBasicFault(String message, AresOdpovedi faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cz.ares.basic.AresOdpovedi
     */
    public AresOdpovedi getFaultInfo() {
        return faultInfo;
    }

}
