
package cz.ares.basic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HttpSoapBasic", targetNamespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/wsdl/basic.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HttpSoapBasic {


    /**
     * Request/response operace pro získání xml výpisu BASIC pøes HTTP ve formátu SOAP
     * 
     * @param request
     * @return
     *     returns cz.ares.basic.AresOdpovedi
     * @throws GetHttpBasicFault
     */
    @WebMethod(operationName = "GetXmlFile")
    @WebResult(name = "Ares_odpovedi", targetNamespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_answer_basic/v_1.0.3", partName = "Answer")
    public AresOdpovedi getXmlFile(
        @WebParam(name = "Ares_dotazy", targetNamespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_request_orrg/v_1.0.0", partName = "Request")
        AresDotazy request)
        throws GetHttpBasicFault
    ;

}
